version: "3.9"

services:
  todo:
    image: postgres:16-alpine
    container_name: todo
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo
    volumes:
      - todo_data:/var/lib/postgresql/data

volumes:
  todo_data:
